install.packages("ggplot2")
install.packages("gridExtra")
install.packages(("dplyr"))
install.packages("RColorBrewer")
install.packages("pheatmap")
 if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install("AnnotationDbi", version = "3.8")
BiocManager::install("tximport", version = "3.8")

